# Streamlit secrets required for InboxKit integration.
# Rename this file to `secrets.toml` in your local `.streamlit` directory and
# provide the actual values before running the app.
INBOXKIT_BASE_URL = "https://api.inboxkit.com"
INBOXKIT_BEARER = ""
INBOXKIT_WORKSPACE_ID = ""
INBOXKIT_UID_LOOKUP_MODE = "auto"
